### PR TITLE
title input image done

### PR DESCRIPTION
**Pull request by Hmullla**
edited contact info

### CODE REVIEW

**Review by mz106 — CHANGES_REQUESTED** [review]
Hannah, please edit contact page title to read "Contact Information Details"

**Review by Hmullla — COMMENTED** [review]
please note two separate h1 tags, one reading contact info and one reading details

**Review by mz106 — COMMENTED** [review]
Ok Hannah, please edit first h1 tag to read "Contact Information". Please leave the second H1 tag alone.

**Review by Hmullla — COMMENTED** [review]
done, please review

**Review by mz106 — APPROVED** [review]
Approved

**Pull request merged**
